apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/java.yml
- base/secret.yml
- base/configmap.yml


commonLabels:
  app: java-app

namespace: pet-clinic-app # Update based on your target namespace

replicas:
  - name: java-app
    count: 3