apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: pet-clinic-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  strategy:
    type: BlueGreen
    blueGreenStrategy:
      activeService: java-app-service
      previewService: java-app-service-preview
      autoPromotionEnabled: true
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app-container
        image: techiescamp/kube-petclinic-app:2.0.0
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-cred
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-cred
                key: password
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: java-app-config
          mountPath: "/opt/config"
        command: ["java", "-javaagent:/app/jmx.jar=9090:/app/config.yml", "-jar", "/app/java.jar", "--spring.config.location=/opt/config/application.properties", "--spring.profiles.active=mysql"]

      volumes:
      - name: java-app-config
        configMap:
          name: java-app-config
