apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: pet-clinic-db
spec:
  selector:
    app: java-app
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30145
  - name: metrics
    protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30147

---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service-preview
  namespace: pet-clinic-db
spec:
  selector:
    app: java-app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
