apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: pet-clinic-db
spec:
  selector:
    app: java-app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service-preview
  namespace: pet-clinic-db
spec:
  selector:
    app: java-app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
